import { StyleSheet } from "react-native";

export const registerScreenStyles = StyleSheet.create({
	containerBig: {
		width: "100%",
		display: "flex",
		flexDirection: "column",
		backgroundColor: "black",
	},
	containerRegisterScreen: {
		display: "flex",
		flexDirection: "column",
		justifyContent: "center",
		alignItems: "center",
		marginTop: 25,
	},
	inputUserInfo: {
		width: 315,
		height: 45,
		lineHeight: 15,
		borderRadius: 15,
		paddingLeft: 25,
		borderColor: "white",
		color: "black",
		borderWidth: 2,
		backgroundColor: "white",
		marginBottom: 20,
	},
	textRegisterScreen: {
		width: 320,
		color: "#ffffff",
		fontSize: 14,
		textAlign: "justify",
		marginBottom: 15,
		marginTop: 10,
		lineHeight: 20,
	},
	containerButtonSelection: {
		display: "flex",
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
	},
	buttonSelection: {
		width: 100,
		height: 37,
		borderRadius: 50,
		borderColor: "white",
		borderWidth: 1,
		margin: 5,
	},
	textButtonSelection: {
		color: "#ffffff",
		fontSize: 19,
		textAlign: "center",
		lineHeight: 37,
		fontWeight: "500",
	},
	buttonAccept: {
		backgroundColor: "#F6163C",
		width: 315,
		height: 65,
		alignSelf: "center",
		borderRadius: 15,
		marginTop: 20,
	},
	textButtonAccept: {
		fontSize: 20,
		fontWeight: "400",
		textAlign: "center",
		color: "white",
		lineHeight: 65,
	},
});
