import { Dimensions, StyleSheet } from "react-native";

const widthScreen = Dimensions.get("window").width;

export const localStyles = StyleSheet.create({
	containerBig: {
		width: "100%",
		flexDirection: "column",
	},
	containerLineSeparator: {
		alignSelf: "center",
		width: "95%",
		height: 2,
		backgroundColor: "#A6A6A6",
		paddingLeft: 10,
		paddingRight: 10,
		marginTop: 10,
		marginBottom: 10,
	},
	containerImageAndIcons: {
		width: "100%",
		height: 245,
		position: "relative",
		padding: 0,
		margin: 0,
	},
	containerIconsInteractive: {
		width: "100%",
		display: "flex",
		flexDirection: "row",
		justifyContent: "space-between",
		paddingLeft: 15,
		paddingRight: 30,
		position: "absolute",
		zIndex: 2,
		top: 40,
	},
	containerIconsInteractiveGroup: {
		width: 65,
		display: "flex",
		flexDirection: "row",
		justifyContent: "space-between",
	},
	iconsInteractiveBack: {
		width: 27,
		height: 27,
	},
	iconsInteractiveShare: {
		width: 27,
		height: 27,
	},
	iconsInteractiveLike: {
		width: 27,
		height: 27,
	},
	imageSlider: {
		width: "100%",
		minHeight: 240,
	},
	containerLocalInfo: {
		width: "100%",
		paddingLeft: 10,
	},
	containerLocalInfoTitle: {
		display: "flex",
		flexDirection: "row",
		flexWrap: "wrap",
		justifyContent: "flex-start",
		alignItems: "center",
	},
	localInfoTitle: {
		fontWeight: "400",
		fontSize: 36,
	},
	localInfoDistance: {
		fontWeight: "400",
		fontSize: 20,
		paddingTop: 10,
	},
	localInfoActivity: {
		fontWeight: "400",
		fontSize: 16,
		marginTop: 12,
	},
	containerInfoReviewAndPrice: {
		display: "flex",
		flexDirection: "row",
		flexWrap: "wrap",
		justifyContent: "flex-start",
		alignItems: "center",
		marginTop: 12,
	},
	imageInfoReview: {
		width: 13,
		height: 13,
	},
	infoReviewAndPrice: {
		paddingLeft: 5,
		fontSize: 16,
		fontWeight: "600",
	},
	infoReviewAndPriceHour: {
		paddingLeft: 5,
		fontWeight: "100",
		color: "#A6A6A6",
	},
	descriptionContainer: {
		paddingLeft: 12,
		marginTop: 12,
	},
	descriptionTitle: {
		fontWeight: "400",
		fontSize: 18,
	},
	descriptionParagraph: {
		fontWeight: "400",
		fontSize: 16,
		lineHeight: 20,
		textAlign: "justify",
		paddingRight: 17,
		marginTop: 5,
	},
	containerServices: {
		paddingLeft: 10,

		display: "flex",
		flexDirection: "column",
		flexWrap: "wrap",
		justifyContent: "flex-start",
	},
	servicesTitle: {
		fontSize: 20,
		fontWeight: "400",
	},
	containerServicesOffered: {
		display: "flex",
		flexDirection: "row",
		flexWrap: "wrap",
	},
	servicesOffered: {
		width: "49%",
		display: "flex",
		flexDirection: "row",
		justifyContent: "flex-start",
		alignItems: "center",
		marginTop: 10,
	},
	servicesOfferedIcons: {
		width: 30,
		height: 25,
	},
	servicesOfferedName: {
		width: 110,
		paddingLeft: 10,
	},
	locationContainer: {
		display: "flex",
		flexDirection: "column",
		justifyContent: "flex-start",
	},
	locationTitle: {
		fontSize: 20,
		fontWeight: "400",
		paddingBottom: 10,
		paddingLeft: 10,
	},
	locationImage: { width: "100%", height: 240 },
	locationAdress: {
		paddingLeft: 10,
		fontSize: 16,
		fontWeight: "400",
		marginTop: 10,
	},
	scheduleContainer: {
		display: "flex",
		flexDirection: "column",
		paddingLeft: 10,
	},
	scheduleTitle: {
		fontSize: 20,
		fontWeight: "400",
		marginBottom: 10,
	},
	containerScheduleByDay: {
		display: "flex",
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		paddingRight: 10,
		paddingTop: 5,
	},
	containerScheduleDay: {
		fontSize: 16,
		fontWeight: "400",
	},
	containerScheduleTime: {
		fontSize: 16,
		fontWeight: "400",
	},
	containerCommunity: {
		width: "100%",
		minHeight: 300,
		display: "flex",
		flexDirection: "column",
		justifyContent: "flex-start",
		alignItems: "flex-start",
		paddingLeft: 14,
		paddingTop: 15,
		color: "#ffffff",
		backgroundColor: "#000000",
		marginTop: 10,
	},
	containerCommuinityTitle: {
		display: "flex",
		flexDirection: "row",
		justifyContent: "flex-start",
		alignItems: "center",
	},
	communityTitleText: {
		fontSize: 25,
		fontWeight: "400",
		color: "#ffffff",
	},
	comunnityTitleLogo: {
		width: 142,
		marginLeft: 4,
		marginRight: 2,
	},
	communityDescription: {
		minWidth: 320,
		maxWidth: 370,
		fontSize: 16,
		fontWeight: "400",
		letterSpacing: 0.6,
		color: "#ffffff",
		paddingTop: 15,
	},
	containerCommunityGroups: {
		width: "100%",
		display: "flex",
		flexDirection: "column",
		justifyContent: "flex-start",
		alignItems: "flex-start",
	},
	communityGroupTitle: {
		fontSize: 20,
		fontWeight: "800",
		color: "#ffffff",
		paddingTop: 15,
	},
	containerCommunityGroupsLives: {
		width: "100%",
		display: "flex",
		flexDirection: "row",
		justifyContent: "flex-start",
		alignItems: "flex-start",
		paddingTop: 15,
	},
	communityGroupListAvatars: {
		minWidth: 50,
		display: "flex",
		flexDirection: "row",
	},
	communityGroupImageAvatar: {
		width: 32,
	},
	containerCommunityGroupsLivesInfo: {
		display: "flex",
		flexDirection: "column",
		paddingLeft: 5,
	},
	communityGroupNameGroup: {
		fontSize: 14,
		fontWeight: "400",
		color: "#ffffff",
	},
	communityGroupDetailGroup: {
		fontSize: 14,
		fontWeight: "400",
		color: "#ffffff",
	},
	communityFooter: {
		fontSize: 16,
		fontWeight: "400",
		color: "#ffffff",
		paddingTop: 20,
	},
	containerReviews: {
		display: "flex",
		flexDirection: "column",
		justifyContent: "flex-start",
		paddingLeft: 14,
		paddingRight: 14,
		paddingBottom: 20,
	},
	containerReviewsTitle: {
		display: "flex",
		flexDirection: "row",
		justifyContent: "flex-start",
		alignItems: "center",
		marginTop: 10,
	},
	reviewTitleIcon: {
		width: 13,
		marginRight: 5,
	},
	reviewTitleText: {
		fontSize: 36,
		fontWeight: "400",
	},
	containerReviewTypes: {
		display: "flex",
		flexDirection: "row",
		flexWrap: "wrap",
		justifyContent: "flex-start",
		alignItems: "center",
		marginTop: 10,
	},
	conainerReviewEachType: {
		width: "49%",
		display: "flex",
		flexDirection: "column",
		justifyContent: "space-between",
		marginTop: 5,
	},
	reviewTypeName: {
		fontSize: 15,
		fontWeight: "400",
		textTransform: "capitalize",
	},
	containerReviewTypeScore: {
		display: "flex",
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "flex-end",
		paddingRight: 10,
	},
	reviewTypeLine: {
		width: 100,
		height: 2,
		backgroundColor: "#000000",
		alignSelf: "center",
		marginRight: 3,
		marginTop: 5,
	},
	reviewTypeValue: {
		fontSize: 16,
		fontWeight: "400",
	},
	containerReviewCard: {
		marginTop: 30,
		height: 184,
		borderWidth: 1,
		borderRadius: 10,
		borderColor: "#000000",
		paddingTop: 15,
		paddingLeft: 10,
		paddingRight: 10,
	},
	containerReviewCardUser: {
		display: "flex",
		flexDirection: "row",
	},
	reviewCardUserAvatar: {
		width: 32,
		height: 32,
		marginRight: 7,
	},
	containerReviewCarUserInfo: {
		display: "flex",
		flexDirection: "column",
	},
	reviewCardUserName: {
		fontSize: 14,
		fontWeight: "900",
	},
	reviewCardUserTimestamp: {
		fontSize: 12,
	},
	reviewCardUserDescription: {
		paddingTop: 16,
		textAlign: "justify",
		fontSize: 16,
		fontWeight: "400",
	},
});
