import { StyleSheet } from "react-native";

export const loginScreenStyles = StyleSheet.create({
	containerBig: {
		width: "100%",
		display: "flex",
		flexDirection: "column",
		backgroundColor: "black",
	},
	containerEmailScreen: {
		width: "100%",
		minHeight: 600,
		display: "flex",
		flexDirection: "column",
		justifyContent: "center",
		alignItems: "center",
	},
	registerInput: {
		width: 315,
		height: 45,
		lineHeight: 15,
		borderRadius: 15,
		paddingLeft: 25,
		borderColor: "white",
		color: "white",
		borderWidth: 2,
		backgroundColor: "white",
	},
	buttonContinueRegister: {
		backgroundColor: "#F6163C",
		width: 315,
		height: 65,
		alignSelf: "center",
		borderRadius: 15,
		marginTop: 25,
	},
	textButtonContinue: {
		fontSize: 20,
		fontWeight: "400",
		textAlign: "center",
		color: "white",
		lineHeight: 65,
	},
	containerSeparator: {
		width: "100%",
		height: 10,
		marginTop: 20,
		marginBottom: 20,
		display: "flex",
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
	},
	lineSeparator: {
		width: 140,
		height: 1,
		backgroundColor: "#e4e5e7",
	},
	circleSeparator: {
		width: 8,
		height: 8,
		marginLeft: 10,
		marginRight: 10,
		borderRadius: 50,
		borderWidth: 1,
		borderColor: "#e4e5e7",
	},
	containerContinueButtonsWays: {
		width: "100%",
		marginTop: 20,
		marginBottom: 20,
		display: "flex",
		flexDirection: "column",
		justifyContent: "center",
		alignItems: "center",
	},
	buttonRegisterOtherWays: {
		width: 315,
		height: 45,
		lineHeight: 15,
		borderRadius: 15,
		paddingLeft: 25,
		borderColor: "white",
		borderWidth: 2,
		backgroundColor: "white",
		display: "flex",
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		marginBottom: 20,
	},
	imageRegisterOtherWays: {
		width: 25,
		height: 25,
	},
	textRegisterOtherWays: {
		color: "black",
		width: 200,
		textAlign: "left",
	},
});
